spring:
  datasource:
    url: jdbc:mysql://localhost:3306/efubassignment?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1023
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # ???? ???? ??
  output:
    ansi:
      enabled: always

server:
  port: 8080

