spring:
  application:
    name: community
  profiles:
    active: dev # 기본값은 dev, 필요시 ${SPRING_PROFILES_ACTIVE} 환경변수로 변경 가능

  datasource:
    url: jdbc:mysql://localhost:3306/blog?createDatabaseIfNotExist=true&characterEncoding=UTF-8&characterSetResults=UTF-8
    username: root
    password: jya7736!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
kakao:
  client_id: 2f5ddb2c178adab2c106ebfad19bcd4e
  redirect_uri: http://localhost:8080/callback
